name: Build RustDesk Client

on:
  workflow_dispatch:  # 允许手动触发工作流
  push:
    branches: [ main ]  # 在main分支有推送时触发

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            artifact_name: rustdesk-linux
            build_command: cargo build --release && strip target/release/rustdesk
          - os: windows-latest
            artifact_name: rustdesk-windows
            build_command: cargo build --release
          - os: macos-latest
            artifact_name: rustdesk-macos
            build_command: cargo build --release

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libvpx-dev \
            libopus-dev \
            libavcodec-dev \
            libavutil-dev \
            libswscale-dev \
            libgtk-3-dev \
            libayatana-appindicator3-dev \
            libsdl2-dev \
            libgl1-mesa-dev \
            libxcb-randr0-dev \
            libxcb-xfixes0-dev \
            libxcb-shape0-dev

      - name: Install macOS dependencies
        if: matrix.os == 'macos-latest'
        run: |
          brew install vpx opus ffmpeg sdl2

      - name: Clone RustDesk repository
        run: git clone https://github.com/rustdesk/rustdesk.git

      - name: Build RustDesk client
        working-directory: ./rustdesk
        run: ${{ matrix.build_command }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: |
            rustdesk/target/release/rustdesk
            rustdesk/target/release/rustdesk.exe
          retention-days: 7
    